DATA hw1;
INFILE '/folders/myfolders/data.csv' DLM = ',' DSD MISSOVER;
INPUT AGE SEX $ BMI CHILDREN SMOKER $ REGION $ CHARGES;
SET hw1;
IF _N_ >= 1334 THEN DELETE;
RUN; 

PROC REG DATA = hw1;
MODEL CHARGES = AGE BMI CHILDREN;
RUN;

DATA hw1_;
INFILE '/folders/myfolders/data.csv' DLM = ',' DSD MISSOVER;
INPUT AGE SEX $ BMI CHILDREN SMOKER $ REGION $ CHARGES;
RUN; 

PROC REG DATA = hw1_;
MODEL CHARGES = AGE BMI CHILDREN;
OUTPUT OUT = hw1out L95 = low95 U95 = high95;
RUN;

PROC PRINT DATA = hw1out;
RUN;