DATA hw2;
INFILE '/folders/myfolders/data.csv' DLM = ',' DSD MISSOVER;
INPUT AGE SEX $ BMI CHILDREN SMOKER $ REGION $ CHARGES;
RUN; 

PROC ANOVA DATA = hw2;
CLASS SEX;
MODEL CHARGES = SEX;
MEANS SEX;
RUN;